### ISSUE TITLE
Paths in v15.6 backup failed

### ISSUE THREAD

**Issue by wobal** [EnterpriseDB/edb-installers#99] opened 2024-02-27 10:23 UTC
2 pb :
- By installing version 15.6, PgAdmin points to version 12 binaries and the backup does not work.
if we specify the pgadmin runtime directory it doesn't work either. 
2 dlls are missing in the pgadmin runtime directory: libzstd.dll and liblz4.dll (
they are present in the bin directory of the postgresql server directory)
And indeed, if we specify the bin directory of the postgresql server the backup works.
- We have a program that looks for the postgresql server path in the windows registry.
Since version 15.6 which is normally a minor version, the version number in the registry contains the minor version and not the major version (15.6 instead of 15 as with versions 10 to 15.4) (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows \CurrentVersion\Uninstall\PostgreSQL 15.6).
Is this normal, why only since the 15.6 version and will it always be like this ?
What would be the best way to know the postgreSQL server directory (pg_dump) chosen by the user ?

Thanks

**Comment by sandeep-edb** [comment] 2024-03-13 13:43
thanks for reporting. they both seem to be bug caused by the changes to the build framework. will be fixed them and release an update.

**Comment by agarwal-kritika** [comment] 2024-05-13 06:12
The issue is fixed in May'24 minor release

**Comment by agarwal-kritika** [comment] 2024-05-13 06:12
The issue is fixed in May'24 minor release.

**Closed as completed by agarwal-kritika** 2024-05-13 06:12 UTC
